[package]
edition = "2021"
name = "fit_utils"
version = "0.1.0"

[dependencies]
anyhow = "1.0.56"
chrono = "0.4.19"
clap = { version="3.1.8", features = ["derive"] }
fitparser = "0.4.3"
flate2 = "1.0.23"
geo-types = "0.7.4"
log = "0.4.16"
serde = "1.0.136"
serde_json = "1.0.79"
